services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - spring-network
    env_file:
      - .env
    restart: always

networks:
  spring-network:
    external: true
    name: spring-network

