ALTER TABLE banner
    ADD IF NOT EXISTS category_id UUID CONSTRAINT FK_BANNER_ON_CATEGORY REFERENCES category (id);

ALTER TABLE banner
    ADD IF NOT EXISTS description VARCHAR(255);

ALTER TABLE banner
    ADD IF NOT EXISTS food_id UUID CONSTRAINT FK_BANNER_ON_FOOD REFERENCES food (id);

ALTER TABLE banner
    ADD IF NOT EXISTS title VARCHAR(255);

ALTER TABLE banner
    ADD IF NOT EXISTS type VARCHAR(255);

ALTER TABLE company
    DROP COLUMN IF EXISTS header_id;