name: CI/CD for Spring Boot with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: '22'
#
#      - name: Build with Maven
#        run: mvn clean package
#
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: packaged-application
#          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-application
          path: target/

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::710271916844:role/GITHUB_ACTION
          role-session-name: GITHUB_ACTION
          aws-region: sa-east-1

      - name: Connect SSH and Restart Services
        run: |
          aws deploy create-deployment \
              --application-name MyMenu \
              --deployment-group-name MY_MENU_AUTOMATED_GROUP \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
