#name: CI/CD for Spring Boot with Maven
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: '22'
#
#      - name: Test with Maven
#        run: mvn -B test
#
#  deploy:
#    needs: test
#    runs-on: ubuntu-latest
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#
#    steps:
#      - name: configure aws credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}
#          role-session-name: ${{secrets.ROLE_SESSION_NAME}}
#          aws-region: ${{secrets.AWS_REGION}}
#
#      - name: Connect SSH and Restart Services
#        run: |
#          aws deploy create-deployment \
#              --application-name MyMenu \
#              --deployment-group-name MY_MENU_AUTOMATED_GROUP \
#              --deployment-config-name CodeDeployDefault.OneAtATime \
#              --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
